version: "3.8"
   
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=musiquarium
      - POSTGRES_USER=musiquarium
      - POSTGRES_PASSWORD=musiquarium
  web:
    build: ./musiquarium_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./musiquarium_site/:/usr/src/musiquarium/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
