# Generated by Django 3.1.1 on 2020-10-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(blank=True, max_length=64, verbose_name='Album')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Year')),
                ('track_total', models.SmallIntegerField(blank=True, null=True, verbose_name='Total track count')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['album', '-artist', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100, verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Artist',
                'ordering': ['artist'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=200, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size', models.IntegerField(editable=False, verbose_name='File size')),
                ('duration', models.IntegerField(default=0, editable=False, verbose_name='Song duration in seconds')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('track_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Track number')),
                ('disc_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Disc number')),
                ('disc_total', models.SmallIntegerField(blank=True, null=True, verbose_name='Total disc count')),
                ('detection_method', models.CharField(default='no detection method set', help_text='Select a genre for this book', max_length=100, verbose_name='Detection method')),
                ('album', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='musiq_site_app.album')),
                ('artist', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='musiq_site_app.artist')),
                ('genre', models.ManyToManyField(blank=True, max_length=64, to='musiq_site_app.Genre')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['title', '-album', '-artist'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='musiq_site_app.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, max_length=64, to='musiq_site_app.Genre'),
        ),
    ]
